/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package top.produits;

import org.junit.Test;;

public class AppTest {
    @Test public void testAppHasAGreeting() {
      
    }
}
