/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package top.produits;

import jbdc.Session;

public class App {
   

    public static void main(String[] args) {
        Session test = new Session();
    }
}
